/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent { 'body1' : string, 'body2' : string }
export interface AdmissionsContent {
  'description' : string,
  'heading' : string,
}
export interface Announcement {
  'title' : string,
  'date' : string,
  'excerpt' : string,
}
export interface ContactContent {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DiscoverTile { 'name' : string }
export type ExternalBlob = Uint8Array;
export interface FooterContent { 'motto' : string }
export interface HeroContent {
  'title' : string,
  'description' : string,
  'subtitle' : string,
}
export interface Highlight { 'title' : string, 'text' : string }
export interface ImageUrls {
  'heroUrl' : [] | [string],
  'logoUrl' : [] | [string],
  'discoverUrls' : Array<string>,
}
export interface LeaderMessage {
  'name' : string,
  'role' : string,
  'message' : string,
  'photo' : [] | [ExternalBlob],
}
export interface SiteContent {
  'contact' : ContactContent,
  'about' : AboutContent,
  'admissions' : AdmissionsContent,
  'messages' : Array<LeaderMessage>,
  'hero' : HeroContent,
  'name' : string,
  'highlights' : Array<Highlight>,
  'discover' : Array<DiscoverTile>,
  'announcements' : Array<Announcement>,
  'footer' : FooterContent,
  'images' : ImageUrls,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'changePin' : ActorMethod<[string, string], boolean>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'updateAbout' : ActorMethod<[string, AboutContent], boolean>,
  'updateAdmissions' : ActorMethod<[string, AdmissionsContent], boolean>,
  'updateAnnouncements' : ActorMethod<[string, Array<Announcement>], boolean>,
  'updateContact' : ActorMethod<[string, ContactContent], boolean>,
  'updateDiscover' : ActorMethod<[string, Array<DiscoverTile>], boolean>,
  'updateFooter' : ActorMethod<[string, FooterContent], boolean>,
  'updateHero' : ActorMethod<[string, HeroContent], boolean>,
  'updateHighlights' : ActorMethod<[string, Array<Highlight>], boolean>,
  'updateImages' : ActorMethod<[string, ImageUrls], boolean>,
  'updateMessages' : ActorMethod<[string, Array<LeaderMessage>], boolean>,
  'verifyPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];